workflows:
  ios-publish:
    name: Build and Publish iOS
    instance_type: mac_mini_m2  # 或 mac_pro 为更快构建
    max_build_duration: 60
    environment:
      vars:
        BUNDLE_ID: "com.jboth.mine"  # 匹配您的 Bundle ID
        APP_NAME: "加步协同"
        MATCH_CERTIFICATE_PATH: "{{ DISTRIBUTION_CERT }}"  # Codemagic 会自动注入
        MATCH_PROVISIONING_PROFILE_UUID: "{{ APP_STORE_PROFILE }}"
    scripts:
      - name: Get packages
        script: yarn install  # 或 npm install，如果用 npm
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build iOS
        script: |
          cd ios
          xcode-project use-profiles
          xcode-project build-ipa --scheme "$APP_NAME"
    artifacts:
      - ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - bill.fan4java@gmail.com  # 测试通知
      app_store_connect:
        api_key: '$jboth_app_store_connect'  # 引用 Codemagic UI 中配置的 API Key
        submit_to_testflight: true  # 先测试，再设为 app_store