workflows:
  ios-publish:
    name: Build and Publish iOS
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        BUNDLE_ID: "com.jboth.mine"  # 主应用 Bundle ID
        APP_NAME: "Mattermost"  # 确认 Scheme
        MATCH_CERTIFICATE_PATH: "{{ DistributionCert }}"  # 证书 Reference name
        MATCH_PROVISIONING_PROFILE_UUID: "{{ AppStoreProfile }}"  # 主应用配置文件
        MATCH_SHARE_PROFILE: "{{ ShareProfile }}"  # MattermostShare 配置文件
        MATCH_NOTIFICATION_PROFILE: "{{ NotificationProfile }}"  # NotificationService 配置文件
        CI: "true"  # 触发跳过 Solidarity
    scripts:
      - name: 1 Clean up parent directory
        script: |
          rm -f /Users/builder/package.json /Users/builder/yarn.lock
      - name: Get packages
        script: |
          cd /Users/builder/clone
          yarn install --frozen-lockfile
      - name: Install CocoaPods
        script: |
          cd /Users/builder/clone/ios
          gem uninstall cocoapods -a -x
          gem install cocoapods -v 1.16.1
          pod cache clean --all
          pod install
      - name: Build iOS
        script: |
          cd /Users/builder/clone/ios
          xcode-project use-profiles
          xcode-project build-ipa --workspace Mattermost.xcworkspace --scheme "$APP_NAME" \
            --export-options-plist "{\"method\":\"app-store\",\"provisioningProfiles\":{\"com.jboth.mine\":\"$MATCH_PROVISIONING_PROFILE_UUID\",\"com.jboth.mine.MattermostShare\":\"$MATCH_SHARE_PROFILE\",\"com.jboth.mine.NotificationService\":\"$MATCH_NOTIFICATION_PROFILE\"}}"
    artifacts:
      - ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - bill.fan4java@gmail.com
      app_store_connect:
        api_key: "$jboth_app_store_connect"
        key_id: "UZ33M397NY"
        issuer_id: "26e601c9-c2f0-497a-a9e1-39a426cecf9a"  # 替换为您的 Issuer ID
        submit_to_testflight: true