workflows:
  mm-whitelabel-ios:
    name: "Mattermost WhiteLabel iOS (TestFlight/App Store)"
    max_build_duration: 120
    environment:
      vars:
        # 与 App Store 类型描述文件匹配
        EXPORT_METHOD: app-store
      groups:
        - ios_match
        - whitelabel_common
        - whitelabel_ios
      xcode: latest
      cocoapods: default
      node: 20.12.2
      npm: 10.5.0
      ruby: 3.3.6
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $HOME/Library/MobileDevice/Provisioning Profiles
        - $CM_BUILD_DIR/node_modules
        - $CM_BUILD_DIR/ios/Pods
        - $CM_BUILD_DIR/ios/build
        - $HOME/Library/Caches/bundle
    scripts:
      - name: 安装 Ruby 工具链与 CocoaPods（固定为 1.16.1）
        script: |
          set -euo pipefail
          gem install cocoapods -v 1.16.1 --no-document
          gem install bundler --no-document
          echo "ruby -v: $(ruby -v)"
          echo "gem -v: $(gem -v)"
          echo "pod --version: $(pod --version)"
      - name: 安装依赖（npm ci）
        script: |
          set -euo pipefail
          npm ci
      - name: pods 安装（pod install）
        script: |
          set -euo pipefail
          cd ios
          pod repo update --silent || true
          pod install --repo-update
          cd -
      - name: "🔧 Patch Pods project for TurboLogIOSNative (remove .modulemap from Compile Sources)"
        script: |
          set -e
          cd ios
          ruby - <<'RUBY'
          require 'xcodeproj'
          proj = Xcodeproj::Project.open('Pods/Pods.xcodeproj')
          t = proj.targets.find { |x| x.name == 'TurboLogIOSNative' }
          if t
            phase = if t.respond_to?(:sources_build_phase)
              t.sources_build_phase
            elsif t.respond_to?(:source_build_phase)
              t.source_build_phase
            else
              nil
            end
            removed = 0
            if phase
              phase.files.each do |bf|
                fr = bf.file_ref
                next unless fr && fr.path
                if fr.path.end_with?('TurboLogSwift/module.modulemap') || fr.path.end_with?('module.modulemap')
                  phase.remove_file_reference(fr)
                  removed += 1
                end
              end
            end
            t.build_configurations.each do |cfg|
              cfg.build_settings['MODULEMAP_FILE'] = '$(SRCROOT)/TurboLogIOSNative/Sources/TurboLogSwift/module.modulemap'
            end
            proj.save
            puts "✅ Removed #{removed} *.modulemap from Compile Sources in TurboLogIOSNative"
          else
            puts "ℹ️ Target TurboLogIOSNative not found"
          end
          RUBY
          cd ..
      - name: "🔎 Assert: no .modulemap left in Compile Sources"
        script: |
          set -e
          cd ios
          ruby - <<'RUBY'
          require 'xcodeproj'
          proj = Xcodeproj::Project.open('Pods/Pods.xcodeproj')
          errors = []
          proj.targets.each do |t|
            phase = if t.respond_to?(:sources_build_phase)
              t.sources_build_phase
            elsif t.respond_to?(:source_build_phase)
              t.source_build_phase
            else
              nil
            end
            next unless phase
            phase.files.each do |bf|
              fr = bf.file_ref
              if fr && fr.path && fr.path.end_with?('module.modulemap')
                errors << "#{t.name}: #{fr.path}"
              end
            end
          end
          if errors.any?
            warn "Found modulemap in Compile Sources:\n  - " + errors.join("\n  - ")
            exit 1
          else
            puts "✅ No module.modulemap in any Compile Sources"
          end
          RUBY
          cd ..
      - name: 替换白标资源与配置（icons / splash / bundle id 等）
        script: |
          set -euo pipefail
          echo ">> 在此执行你仓库已有的白标资源替换与 Info.plist / entitlements / Team ID 调整"
      - name: 打印必须的环境变量（安全检查）
        script: |
          set -euo pipefail
          echo "CM_REPO_SLUG=${CM_REPO_SLUG}"
          echo "APP_DISPLAY_NAME=${APP_DISPLAY_NAME}"
          echo "BUNDLE_ID=${BUNDLE_ID}"
          echo "BUNDLE_ID_SHARE=${BUNDLE_ID_SHARE}"
          echo "BUNDLE_ID_NOTI=${BUNDLE_ID_NOTI}"
          echo "TEAM_ID=${TEAM_ID}"
          echo "PROVISIONING_GIT_URL 已在组变量中设置"
          echo "EXPORT_METHOD=${EXPORT_METHOD}"
      - name: 构建 iOS（使用仓库 lane）
        script: |
          set -euo pipefail
          npm run build:ios
      - name: 收集制品
        script: |
          set -euo pipefail
          mkdir -p build_outputs
          # 依据你仓库的输出路径拷贝 IPA / dSYM / xcarchive
          # cp ./ios/*.ipa build_outputs/ || true
          # cp -R ~/Library/Developer/Xcode/Archives/*/*.xcarchive build_outputs/ || true
    artifacts:
      - build_outputs/**/*

  mm-whitelabel-android:
    name: "Mattermost WhiteLabel Android"
    max_build_duration: 120
    environment:
      groups:
        - whitelabel_common
        - whitelabel_android
      node: 20.12.2
      npm: 10.5.0
      java: 17
    scripts:
      - name: 安装依赖
        script: |
          set -euo pipefail
          npm ci
      - name: 构建 Android（使用仓库脚本）
        script: |
          set -euo pipefail
          npm run build:android
    artifacts:
      - android_build_outputs/**/*
