workflows:
  ios-mattermost-release:
    name: Mattermost iOS (App Groups + Push, no Expo)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      groups:
        - ios_match
      vars:
        APP_NAME: "Mattermost"
        MAIN_BUNDLE_ID: "com.jboth.mine"
        SHARE_BUNDLE_ID: "com.jboth.mine.MattermostShare"
        NOTI_BUNDLE_ID: "com.jboth.mine.NotificationService"
        APP_GROUP_ID: "group.com.jboth.mine"
        CI: "true"
      ios_signing:
        # Let Codemagic fetch matching certificate(s)/profile(s) you uploaded/fetched
        # for this bundle id and its extensions (Share/Notification).
        distribution_type: ad_hoc   # app_store | ad_hoc | development | enterprise
        bundle_identifier: com.jboth.mine

    scripts:
      - name: Xcode version
        script: |
          xcodebuild -version

      - name: Install tools
        script: |
          brew update || true
          brew install jq || true

      - name: Set bundle identifiers & entitlements
        script: |
          bash scripts/setup_signing.sh

      - name: Install pods
        script: |
          cd ios
          pod install --repo-update

      - name: Apply provisioning profiles to Xcode project
        script: |
          # This uses the uploaded/fetched profiles referenced by ios_signing above
          xcode-project use-profiles

      - name: Generate export options (ad-hoc)
        script: |
          cat > export_options.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>ad-hoc</string>
            <key>signingStyle</key><string>manual</string>
            <key>destination</key><string>export</string>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          EOF

      - name: Build archive
        script: |
          cd ios
          xcodebuild -workspace Mattermost.xcworkspace             -scheme Mattermost             -configuration Release             -archivePath build/ios/xcarchive/Mattermost.xcarchive             CODE_SIGN_STYLE=Manual             COMPILER_INDEX_STORE_ENABLE=NO             archive | xcpretty && exit ${PIPESTATUS[0]}

      - name: Export IPA
        script: |
          cd ios
          xcodebuild -exportArchive             -archivePath build/ios/xcarchive/Mattermost.xcarchive             -exportPath ipa             -exportOptionsPlist ../export_options.plist | xcpretty && exit ${PIPESTATUS[0]}

    artifacts:
      - ios/ipa/*.ipa
      - ios/build/**/*.xcarchive

    publishing:
      app_store_connect:
        api_key: "$APP_STORE_CONNECT_PRIVATE_KEY"
        key_id: "$APP_STORE_CONNECT_KEY_ID"
        issuer_id: "$APP_STORE_CONNECT_ISSUER_ID"
        submit_to_testflight: true
      email:
        recipients:
          - bill.fan4java@gmail.com
